"""Added username and body columns to Message

Revision ID: 200a0d5dcf6b
Revises: b0f360aa46b5
Create Date: 2025-04-03 19:14:35.692934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200a0d5dcf6b'
down_revision = 'b0f360aa46b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'username')
    # ### end Alembic commands ###
